# Generated by Django 5.1.6 on 2025-02-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gunpla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("series", models.CharField(max_length=120)),
                ("grade", models.CharField(max_length=50)),
                ("scale", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
