"""Initial migration

Revision ID: baf303d6ba4a
Revises: 
Create Date: 2025-02-21 08:55:54.423043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf303d6ba4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gunpla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('series', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('scale', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gunpla')
    # ### end Alembic commands ###
